version: '3'
volumes:
  db: {}
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=issue
      - POSTGRES_USER=gustjd887
      - POSTGRES_PASSWORD=gustjd25
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"